/**
 * Copied from IsaacSaveFile.js.
 *
 * @public
 */
export enum ChunkType {
  ACHIEVEMENTS = 1,
  COUNTERS = 2,
  LEVEL_COUNTERS = 3,
  COLLECTIBLES = 4,
  MINIBOSSES = 5,
  BOSSES = 6,
  CHALLENGE_COUNTERS = 7,
  CUTSCENE_COUNTERS = 8,
  GAME_SETTINGS = 9,
  SPECIAL_SEED_COUNTERS = 10,
  BESTIARY_COUNTERS = 11,
}
